version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Vladivostok
      #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      #- OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - /mnt/0/documents/projects/pc_settings/calibre/books/:/books
    ports:
      - 8083:8083
    restart: unless-stopped
