version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Vladivostok
    volumes:
      - ./config:/config
      - ./books/:/books
    ports:
      - 8083:8083
    restart: unless-stopped
